#ifndef PARAMS_H
#define PARAMS_H

#define SLICES 30
#define STACKS 20

// RADIUS 
#define SUN_RADIUS 500.0f
#define THIMBER_HEARTH_RADIUS SUN_RADIUS / 6.0f
#define BRITTLE_HOLLOW_RADIUS SUN_RADIUS / 6.0f
#define GIANTS_DEEP_RADIUS SUN_RADIUS / 2.2f
#define DARK_BRAMBLE_RADIUS SUN_RADIUS / 2.2f
#define INTERLOPER_RADIUS SUN_RADIUS / 20.0f
#define WHITE_HOLE_RADIUS SUN_RADIUS / 35.0f
#define QUANTUM_MOON_RADIUS SUN_RADIUS / 20.0f

// DISTANCE
#define THIMBER_HEARTH_DISTANCE SUN_RADIUS + THIMBER_HEARTH_RADIUS + ((SUN_RADIUS + THIMBER_HEARTH_RADIUS) / 2.0f)
#define BRITTLE_HOLLOW_DISTANCE THIMBER_HEARTH_DISTANCE + 2 * BRITTLE_HOLLOW_RADIUS + 2 * THIMBER_HEARTH_RADIUS
#define GIANTS_DEEP_DISTANCE BRITTLE_HOLLOW_DISTANCE + 2 * GIANTS_DEEP_RADIUS + 2 * BRITTLE_HOLLOW_RADIUS
#define DARK_BRAMBLE_DISTANCE GIANTS_DEEP_DISTANCE + 2 * DARK_BRAMBLE_RADIUS + 2 * GIANTS_DEEP_RADIUS
#define INTERLOPER_DISTANCE DARK_BRAMBLE_DISTANCE + 2 * DARK_BRAMBLE_RADIUS + INTERLOPER_RADIUS

// controle da animação
#define INTERLOPER_ANIMATION_PARAMS SUN_RADIUS, INTERLOPER_DISTANCE

#define WHITE_HOLE_TX -SUN_RADIUS * 7.0f
#define WHITE_HOLE_TY 0.0f
#define WHITE_HOLE_TZ 0.0f

// RAIO, R, G, B, SLICES, STACKS
#define SUN_PARAMS SUN_RADIUS, SLICES * 4, STACKS * 4

// RAIO, DISTANCIA DO SOL, TRANSLAÇÃO INICIAL, R, G, B, SLICES, STACKS
#define THIMBER_HEARTH_PARAMS THIMBER_HEARTH_RADIUS, THIMBER_HEARTH_DISTANCE, 0.0f, SLICES, STACKS
#define BRITTLE_HOLLOW_PARAMS BRITTLE_HOLLOW_RADIUS, BRITTLE_HOLLOW_DISTANCE, 0.0f, SLICES, STACKS
#define GIANTS_DEEP_PARAMS GIANTS_DEEP_RADIUS, GIANTS_DEEP_DISTANCE, 0.0f, SLICES * 3, STACKS * 3
#define DARK_BRAMBLE_PARAMS DARK_BRAMBLE_RADIUS, DARK_BRAMBLE_DISTANCE, 0.0f, SLICES * 3, STACKS * 3
#define INTERLOPER_PARAMS INTERLOPER_RADIUS, INTERLOPER_ANIMATION_PARAMS, SLICES, STACKS
#define WHITE_HOLE_PARAMS WHITE_HOLE_RADIUS, SLICES, STACKS, WHITE_HOLE_TX, WHITE_HOLE_TY, WHITE_HOLE_TZ
#define QUANTUM_MOON_PARAMS QUANTUM_MOON_RADIUS, SLICES, STACKS

#endif