#ifndef PARAMS
#define PARAMS

#define SLICES 50
#define STACKS 50

// COLOR (COLOCAR ISSO NO DENTRO DE CADA PLANETA INDIVIDUALMENTE)
#define THIMBER_HEARTH_COLOR 0.0f, 0.0f, 200.0f/255.0f
#define DARK_BRAMBLE_COLOR 255.0f/255.0f, 255.0f/255.0f, 255.0f/255.0f

// RADIUS 
#define SUN_RADIUS 50.0f
#define THIMBER_HEARTH_RADIUS SUN_RADIUS / 12.0f
#define BRITTLE_HOLLOW_RADIUS SUN_RADIUS / 12.0f
#define GIANTS_DEEP_RADIUS SUN_RADIUS / 3.0f
#define DARK_BRAMBLE_RADIUS SUN_RADIUS / 3.0f
#define INTERLOPER_RADIUS SUN_RADIUS / 40.0f

// DISTANCE
#define THIMBER_HEARTH_DISTANCE SUN_RADIUS + THIMBER_HEARTH_RADIUS + ((SUN_RADIUS + THIMBER_HEARTH_RADIUS) / 2.0f)
#define BRITTLE_HOLLOW_DISTANCE THIMBER_HEARTH_DISTANCE + 2 * BRITTLE_HOLLOW_RADIUS + 2 * THIMBER_HEARTH_RADIUS
#define GIANTS_DEEP_DISTANCE BRITTLE_HOLLOW_DISTANCE + 2 * GIANTS_DEEP_RADIUS + 2 * BRITTLE_HOLLOW_RADIUS
#define DARK_BRAMBLE_DISTANCE GIANTS_DEEP_DISTANCE + 2 * DARK_BRAMBLE_RADIUS + 2 * GIANTS_DEEP_RADIUS
#define INTERLOPER_DISTANCE DARK_BRAMBLE_DISTANCE + DARK_BRAMBLE_RADIUS + INTERLOPER_RADIUS

// controle da animação
#define INTERLOPER_ANIMATION_PARAMS SUN_RADIUS, INTERLOPER_DISTANCE

// RAIO, R, G, B, SLICES, STACKS
#define SUN_PARAMS SUN_RADIUS, SUN_COLOR, SLICES, STACKS

// RAIO, DISTANCIA DO SOL, TRANSLAÇÃO INICIAL, R, G, B, SLICES, STACKS
#define THIMBER_HEARTH_PARAMS THIMBER_HEARTH_RADIUS, THIMBER_HEARTH_DISTANCE, 0.0f, THIMBER_HEARTH_COLOR, SLICES, STACKS
#define BRITTLE_HOLLOW_PARAMS BRITTLE_HOLLOW_RADIUS, BRITTLE_HOLLOW_DISTANCE, 0.0f, SLICES, STACKS
#define GIANTS_DEEP_PARAMS GIANTS_DEEP_RADIUS, GIANTS_DEEP_DISTANCE, 0.0f, SLICES, STACKS
#define DARK_BRAMBLE_PARAMS DARK_BRAMBLE_RADIUS, DARK_BRAMBLE_DISTANCE, 0.0f, DARK_BRAMBLE_COLOR, SLICES, STACKS
#define INTERLOPER_PARAMS INTERLOPER_RADIUS, INTERLOPER_ANIMATION_PARAMS, 0.0f, SLICES, STACKS

#endif